apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-data-pvc
  namespace: blog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: ghost-blog