apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-data-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  gcePersistentDisk:
    pdName: ghost-data-pv
    fsType: ext4
