apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-data-pv
  namespace: blog
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/ghost-data
  persistentVolumeReclaimPolicy: Retain