apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-blog-pvc
  labels:
    app: traefik
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
