apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-data-pv
  namespace: blog
spec:
  storageClassName: standard
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
