apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-blog-pvc
  labels:
    app: ghost-blog
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  