apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-blog-pv
  namespace: blog
  labels:
    app: ghost-blog
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: ghost-blog-disk
    fsType: ext4
