apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-blog-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: ghost-blog-disk
    fsType: ext4
