apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-blog-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: standard
  selector:
    matchLabels:
      name: ghost-blog-pv
