apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: blog
  labels:
    app: mysql
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mysql-disk
    fsType: ext4
    
