apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: blog
  labels:
    app: nginx-ingress
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: nginx-ingress-disk
    fsType: ext4