apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-proxy-pvc
  namespace: blog
  labels:
    app: nginx-proxy
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  