apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: blog
  labels:
    app: nginx-proxy
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: nginx-proxy-disk
    fsType: ext4