apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-proxy-pvc
  namespace: blog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: nginx-proxy
