apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-ingress-pvc
  namespace: blog
  labels:
    app: nginx-ingress
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  