apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-proxy-pv
  namespace: blog
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/nginx-proxy"
  persistentVolumeReclaimPolicy: Retain