apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-pv
  namespace: blog
  labels:
    app: traefik
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: traefik-disk
    fsType: ext4
