apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-pv
  labels:
    app: traefik
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: traefik-disk
    fsType: ext4
