apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-blog
  namespace: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghost-blog
  template:
    metadata:
      labels:
        app: ghost-blog
    spec:
      containers:
      - name: ghost-blog
        image: ghost:latest
        ports:
        - containerPort: 2368
        env:
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: mysql-service
        - name: database__connection__user
          value: $(MYSQL_USER)
        - name: database__connection__password
          value: $(MYSQL_PASSWORD)
        - name: url
        resources:
          limits:
            cpu: "0.5"
            memory: "1Gi"
          requests:
            cpu: "0.1"
            memory: "512Mi"
        volumeMounts:
        - name: ghost-persistent-storage
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-persistent-storage
        persistentVolumeClaim:
          claimName: ghost-pvc

