apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-blog-deployment
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-blog
  template:
    metadata:
      labels:
        app: ghost-blog
    spec:
      containers:
      - name: ghost-blog
        image: ghost:latest
        ports:
        - containerPort: 2368
        env:
        - name: url
          valueFrom:
            configMapKeyRef:
              name: ghost-config
              key: url
        - name: database__client
          valueFrom:
            secretKeyRef:
              name: ghost-secrets
              key: database__client
        - name: database__connection__host
          valueFrom:
            secretKeyRef:
              name: ghost-secrets
              key: database__connection__host
        - name: database__connection__user
          valueFrom:
            secretKeyRef:
              name: ghost-secrets
              key: database__connection__user
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: ghost-secrets
              key: database__connection__password
        - name: database__connection__database
          valueFrom:
            secretKeyRef:
              name: ghost-secrets
              key: database__connection__database
        resources:
          limits:
            cpu: "200m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
        - name: ghost-data
          mountPath: /var/lib/ghost/content

