apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx-proxy
        image: nginx:latest
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: nginx-proxy-data
          mountPath: /etc/nginx
      volumes:
      - name: nginx-proxy-data
        persistentVolumeClaim:
          claimName: nginx-proxy-data-pvc
