apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-proxy
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-proxy
  template:
    metadata:
      labels:
        app: traefik-proxy
    spec:
      containers:
      - name: traefik-proxy
        image: traefik:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: traefik-config
          mountPath: /etc/traefik
        - name: traefik-data
          mountPath: /data/traefik
        args:
        - --api
        - --entrypoints.web.address=:80
        - --entrypoints.websecure.address=:443
        - --certificatesresolvers.myresolver.acme.tlschallenge=true
        - --certificatesresolvers.myresolver.acme.email=example@example.com
        - --certificatesresolvers.myresolver.acme.storage=/data/traefik/acme.json
        
        
      # volumes:
      # - name: traefik-config
      #   configMap:
      #     name: traefik-config
      # - name: traefik-data
      #   persistentVolumeClaim:
      #     claimName: traefik-data
