apiVersion: v1
kind: Service
metadata:
  name: ghost-blog-service
spec:
  selector:
    app: ghost-blog
  ports:
  - name: http
    port: 80
    targetPort: 2368
  - name: https
    port: 443
    targetPort: 2368
  type: ClusterIP
