apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  name: nginx
spec:
  ports:
    - name: http-redirect
      port: 80
    - name: ghost-https
      port: 443
  selector:
    app: nginx-proxy
  type: LoadBalancer
  loadBalancerIP: 104.196.166.162