apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: blog
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $host;
      proxy_pass_request_headers on;
spec:
  rules:
    - host: $(VAR_HOST)
      http:
        paths:
          - path: /
            pathType: Prefix
            pathRewrite: /ghost/
            backend:
              service:
                name: ghost-blog-service
                port:
                  name: http
                path: /
  tls:
    - hosts:
        - $(VAR_HOST)
      secretName: $(SECRET_NAME)
